# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FretelloCodingChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FretelloCodingChallenge
	pod 'SnapKit', '~> 5.0'
	pod 'Kingfisher', '~> 6.0'
  target 'FretelloCodingChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FretelloCodingChallengeUITests' do
    # Pods for testing
  end

end
